# orveus version 2022-03-24

version: '3.9'

services:
  gateway:
    container_name: orveus-gateway
    image: orveus/orveus:orveus-gateway
    restart: always
    ports:
      - "443:4040"
      - "80:3030"
    depends_on:
      - backend
      - frontend
    environment:
      - FRONTEND_URL=http://frontend:1338/
      - BACKEND_URL=http://backend:1337/
      - NGINX_SECURE_PORT=4040
      - NGINX_INSECURE_PORT=3030
      - CLIENT_MAX_BODY_SIZE=30M
      - SERVER_NAME=localhost
      - NGINX_PUBLIC_SECURE_PORT=443
    volumes:
      - ./ssl:/etc/nginx/certs

  frontend:
    container_name: orveus-frontend
    image: orveus/orveus:orveus-frontend
    restart: always
    expose:
      - 1338
    depends_on:
      - backend
    environment:
      - NGINX_PORT=1338

  backend:
    container_name: orveus-backend
    image: orveus/orveus:orveus-backend
    restart: always
    expose:
      - 1337
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://db:1433;databaseName=orveus;encrypt=true;trustServerCertificate=true
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=Z87hQ2vQtNt9xq5UMUa6DVD5N
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - UPLOADS_DIR=/data/uploads
      # - SECURITY_JWT_SECRET=<JWT_SECRET_HS512> use your own jwt secret

  db:
    container_name: orveus-db
    image: mcr.microsoft.com/mssql/server:2019-CU14-ubuntu-20.04
    restart: always
    ports:
      - "1435:1433"
    expose:
      - 1433
    command: /bin/sh -c "(/opt/mssql/bin/sqlservr &) && sleep 120s && /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $${SA_PASSWORD} -d master -Q 'CREATE DATABASE orveus;' && sleep infinity"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $${SA_PASSWORD} -d orveus -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 5s
      retries: 100
      start_period: 60s
    environment:
      - SA_PASSWORD=Z87hQ2vQtNt9xq5UMUa6DVD5N #Important note: This password needs to include at least 8 characters of at least three of these four categories: uppercase letters, lowercase letters, numbers and non-alphanumeric symbols.
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - MSSQL_DB=orveus
    volumes:
      - ./database/backups:/var/opt/mssql/backups
      - ./database/data:/var/opt/mssql/data
      - ./database/log:/var/opt/mssql/log
      - ./database/secrets:/var/opt/mssql/secrets
